# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-19 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(error_messages={'unique': 'An account with this email exist.'}, max_length=255, unique=True),
        ),
    ]
